### PR TITLE
Added ability to specify vc category

### PR DESCRIPTION
**Pull request by dylian94**
Requested on the support server by someone, decided to give it a shot.

### CODE REVIEW

**Comment by gregzaal** [comment]
Nice :) At first glance this looks great 👍 
My pc is dead atm so I won't be able to test and merge for maybe another week, but I can't see any immediately obvious issues.

**Comment by gregzaal** [comment]
@dylian94 I assume you've been using this for a while, is it confirmed to be stable?

**Comment by dylian94** [comment]
No issues so far, but we don't use this specific feature on our servers. I mainly made it for the user in the support server who requested it. I had no use for it myself other than getting to know the bot's code a bit better.

**Comment by gregzaal** [comment]
A user reported this error, so I reverted the merge.

```py
Ignoring exception in on_voice_state_update
Traceback (most recent call last):
  File "/home/container/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "/home/container/auto-voice-channels.py", line 1190, in on_voice_state_update
    await func.create_secondary(guild, after.channel, member)
  File "/home/container/utils.py", line 41, in tmp
    return await func(*args, **kwargs)
  File "/home/container/functions.py", line 1090, in create_secondary
    if settings['auto_channels'][primary.id]['category'] is not None:
KeyError: 'category'
```

**Pull request merged**
