### PR TITLE
Fix encoding issue

### PR DESCRIPTION
**Pull request by bl0m1**
Fixed an issue causing channels not to be renamed due to an encoding issue

Issue is reported in https://github.com/gregzaal/Auto-Voice-Channels/issues/66

### CODE REVIEW

**Comment by gregzaal** [comment]
Afaik this shouldn't be necessary if your dev environment is set up correctly. You, shouldn't have to manually encode every print statement.

**Comment by bl0m1** [comment]
@gregzaal If you have another set of install instructions than the one in on the README in the master branch it would be super helpful. Since at least 2 different persons have had the same issue.

**Comment by gregzaal** [comment]
The other issue you commented on has literally nothing to do with this, and afaik only once have I heard someone have the same issue in our support server, and everyone agreed that there was an easy fix they could do in their own environment (don't recall what exactly, probably just google your error message) without needing to compromise the setup of everyone else by changing the codebase.

**Comment by ChillFish8** [comment]
You error is todo with your console's encoding format not python

**Comment by bl0m1** [comment]
If this doesn't work on a default ubuntu 18.04 or 20.04 server I would arguer that this is an issue. If you aren't willing to implement a code fix I assume some documentation should be needed.

To argue that this is a fixe that anyone can do in a couple of minutes is just pure nonsense and defeats the entire point of having information on how to install the bot at all.

**Comment by gregzaal** [comment]
No sure about ubuntu but it works just fine in debian and windows out of the box. I regularly set up fresh installs of this bot on clean new debian servers for patrons, so I know it's fine there.

**Comment by ChillFish8** [comment]
this very much is not an issue with OS *AT ALL* your error extends from the console's stdout and stderr pipes which wont be utf-8 encoded and probably ansi which does not support Emojis or any utf-8 or utf-16 items. You can replicate this error on whatever OS if you set your console to that mode. This shouldnt be something we need to doument as you can solve this by just googling the error.

**Pull request closed without merging**
